name: '[client] EAS Update (OTA)'

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Update channel'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production
      message:
        description: 'Update message'
        required: true
        type: string

defaults:
  run:
    working-directory: ./client

jobs:
  update:
    name: Publish OTA Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Publish update
        run: eas update --channel ${{ inputs.channel }} --message "${{ inputs.message }}" --platform android
        env:
          CI: '1'
          APP_ENV: ${{ inputs.channel }}
